language: generic 
sudo: required
services:
     - docker

before_install:
     - docker build -t nikhil/docker-react -f Dockerfile.dev .

#-- --coverage is to return from hanging test suite o/p.
script:
     - docker run nikhil/docker-react npm run test -- --coverage

deploy:
     provider: elasticbeanstalk
     region: "us-east-2"
     app: "docker-react"
     env: "DockerReact-env"
     bucket_name: "elasticbeanstalk-us-east-2-405484820496"
     bucket_path: "docker-react"
     on:
          branch: master
     access_key_id: $AWS_ACCESS_KEY
     secret_access_key: $AWS_SECRET_KEY 